general:
  seed: 42
  algo: "ga+cv"

data:
  X: "samples/Qin2014/Xtrain.tsv"
  y: "samples/Qin2014/Ytrain.tsv"
  Xtest: "samples/Qin2014/Xtest.tsv"
  ytest: "samples/Qin2014/Ytest.tsv"
  feature_minimal_prevalence: 5 # per class, e.g. if any of the class reaches this level
  feature_maximal_pvalue: 0.8 # feature with differences less significant than this will be removed

ga:
  population_size: 1000
  epochs: 100
  min_epochs: 100
  max_divergence: 0.01
  kmin: 1
  kmax: 50
  kpenalty: 0.003
  select_elite_pct: 25
  select_random_pct: 25
  mutated_individuals_pct: 80
  mutated_features_pct: 10
  mutation_non_null_chance_pct: 5