general:
  seed: 42

data:
  X: "samples/Qin2014/Xtrain.tsv"
  y: "samples/Qin2014/Ytrain.tsv"
  feature_minimal_prevalence: 10 # per class, e.g. if any of the class reaches this level

ga:
  population_size: 1000
  epochs: 100
  kmin: 1
  kmax: 50
  kpenalty: 0.003
  select_elite_pct: 25
  select_random_pct: 25
  mutated_individuals_pct: 10
  mutated_features_pct: 10
  mutation_non_null_chance_pct: 5